#!/usr/bin/env bash
# scripts/setup.sh — zero-config dev bootstrap for dotfiles-core (`make setup`).
# ──────────────────────────────────────────────────────────────────────────────
# Onboarding was implicit: a contributor had to read ci.yml, then hand-install the
# linters (luacheck, nvim, markdownlint, shellcheck) at the right pinned versions,
# then find `make hooks`. This does it in one command, reading the versions from the
# single source (scripts/tool-versions.env) so a local box matches CI:
#   1. install the pre-commit hooks (author-time mirror of CI)
#   2. doctor: report each linter's state against its pin
#   3. run the audit so the box is proven green before you start
#
# Best-effort + graceful, exactly like the other gate scripts: a missing tool is a
# SKIP with the install hint, never a hard stop. Safe to re-run (idempotent).
# ──────────────────────────────────────────────────────────────────────────────
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HERE" || exit 1

# shellcheck source=scripts/lib/common.sh
source "${BASH_SOURCE[0]%/*}/lib/common.sh"

# Read a pinned version out of the single source (no `source`, so no shellcheck
# follow needed — mirrors how audit-core.sh reads the same file).
VERSIONS="scripts/tool-versions.env"
_ver() { sed -n "s/^$1=//p" "$VERSIONS" 2>/dev/null | head -n1; }

# Dim follow-up "→" hint line (the fix-it, after a skip/warn) — one consistent voice
# for the actionable next step, mirroring zsh/ui.zsh's _core_hint in the runtime layer.
hint() { printf '%s→%s %s\n' "$c_yel" "$c_rst" "$*"; }

# --doctor runs ONLY the read-only version doctor (section 3): no installs, no audit —
# the fast `make doctor` triage path for "is my toolchain aligned with CI?". Default
# (no flag) is the full bootstrap (install + doctor + audit).
DOCTOR_ONLY=0
case "${1:-}" in
--doctor) DOCTOR_ONLY=1 ;;
-h | --help)
  cat <<'EOF'
usage: setup.sh [--doctor] [-h|--help]

Zero-config dev bootstrap: install the pre-commit hooks + the pinned toolchain, report
each linter against its pin, then run the audit so the box is proven green.

  --doctor    ONLY the read-only version doctor — no install, no audit (the quick
              `make doctor` triage: which tools are present and do they match the pins?)
  -h, --help  show this help and exit
EOF
  exit 0
  ;;
"") ;;
*)
  printf 'setup.sh: unexpected argument: %s\n' "$1" >&2
  printf 'try: setup.sh --help\n' >&2
  exit 2
  ;;
esac

# ── 1. pre-commit hooks ───────────────────────────────────────────────────────
if ((!DOCTOR_ONLY)); then
  hdr "pre-commit hooks"
  PRECOMMIT_VERSION="$(_ver PRECOMMIT_VERSION)"
  if have pre-commit; then
    if pre-commit install >/dev/null 2>&1; then pass "pre-commit hooks installed"; else fail "pre-commit install failed"; fi
  elif have pipx; then
    if pipx install "pre-commit==${PRECOMMIT_VERSION}" >/dev/null 2>&1 && pre-commit install >/dev/null 2>&1; then
      pass "pre-commit ${PRECOMMIT_VERSION} installed via pipx + hooks wired"
    else fail "pipx install pre-commit failed"; fi
  else
    skip "pre-commit absent — install it: pipx install pre-commit==${PRECOMMIT_VERSION}"
  fi

  # ── 2. hermetic dev toolchain via mise (best-effort) ──────────────────────────
  # This script's header promises a "local hermetic bootstrap [that] installs … to
  # these same versions" — this step is that install (it was previously only the
  # doctor below). mise is already part of the Core stack (mise/config.toml) and
  # tool-versions.env is the single pin source, so generate a GITIGNORED, repo-local
  # mise.local.toml from it and let `mise install` provision the linters the audit/CI
  # run. Best-effort + graceful like every other step: no mise → a hint, not a hard
  # stop; a tool mise can't supply just stays missing and the doctor below flags it.
  # luacheck has no clean mise source (luarocks) so step 2b below provisions it; pre-commit
  # is handled in step 1. The generated file is regenerated every run (idempotent) and is
  # NOT tracked — bumping a pin in tool-versions.env and re-running propagates here.
  hdr "hermetic dev toolchain (mise)"
  if have mise; then
    MISE_LOCAL="mise.local.toml"
    {
      echo "# GENERATED by scripts/setup.sh from $VERSIONS — do not edit by hand."
      echo "# Gitignored, repo-local dev toolchain (the linters the audit/CI run)."
      echo "# Re-run \`make setup\` after bumping a pin to regenerate. \`mise install\` reads this."
      echo "[tools]"
      echo "shellcheck = \"$(_ver SHELLCHECK_VERSION)\""
      echo "actionlint = \"$(_ver ACTIONLINT_VERSION)\""
      echo "neovim = \"$(_ver NVIM_VERSION)\""
      echo "\"npm:markdownlint-cli2\" = \"$(_ver MARKDOWNLINT_VERSION)\""
    } >"$MISE_LOCAL"
    pass "wrote $MISE_LOCAL (pins read from $VERSIONS)"
    mise trust "$MISE_LOCAL" >/dev/null 2>&1
    if mise install >/dev/null 2>&1; then
      pass "mise install provisioned the pinned toolchain"
    else
      printf '%s⚠%s mise install could not provide every tool — the version doctor below shows what is still missing (install those by hand; see ci.yml)\n' "$c_yel" "$c_rst"
    fi
  else
    skip "mise absent — install it (https://mise.jdx.dev) to auto-provision the pinned toolchain; the doctor below lists what to install manually"
  fi

  # ── 2b. luacheck via luarocks (no clean mise source) ──────────────────────────
  # luacheck is a luarocks package — mise has no first-class source for it, so step 2
  # can't provision it and it used to be left wholly manual ("see ci.yml"). Close that
  # gap the same way CI does: when it's missing AND luarocks is present, install the
  # pinned version with --local (lands in ~/.luarocks/bin). Best-effort + graceful: no
  # luarocks → a precise hint, not a hard stop; the doctor below still reports the result.
  hdr "luacheck (luarocks)"
  LUACHECK_VERSION="$(_ver LUACHECK_VERSION)"
  if have luacheck; then
    pass "luacheck already installed"
  elif have luarocks; then
    if luarocks --local install luacheck "$LUACHECK_VERSION" >/dev/null 2>&1; then
      pass "luacheck ${LUACHECK_VERSION} installed via luarocks (--local)"
      # ~/.luarocks/bin is where --local drops the binary; surface it if it's not on PATH.
      case ":$PATH:" in
      *":$HOME/.luarocks/bin:"*) ;;
      *) hint "add \$HOME/.luarocks/bin to PATH so luacheck resolves: export PATH=\"\$HOME/.luarocks/bin:\$PATH\"" ;;
      esac
    else
      hint "luarocks present but 'luarocks --local install luacheck ${LUACHECK_VERSION}' failed — install lua + a dev toolchain, then retry"
    fi
  else
    skip "luacheck absent and luarocks not found — install luarocks, then: luarocks --local install luacheck ${LUACHECK_VERSION}"
  fi

fi # end install steps (1–2b) — skipped by --doctor

# ── 3. version doctor (present? vs the pin) ───────────────────────────────────
hdr "tool versions (pinned in $VERSIONS)"
_doctor() { # _doctor <bin> <pinned> <version-cmd...>
  local bin="$1" want="$2"
  shift 2
  if ! have "$bin"; then
    skip "$bin absent (CI pins $want) — see ci.yml for the install path"
    return
  fi
  # Each tool formats --version differently; capture once, then prefer a full X.Y.Z
  # semver (every pin in tool-versions.env is 3-part) and fall back to X.Y. Matching the
  # FIRST 2-part token outright would mis-read strings like "tool 2024.1 (lib 1.2.3)" —
  # it'd report 2024.1 instead of the real 1.2.3.
  local out got
  out="$("$@" 2>&1)"
  got="$(printf '%s\n' "$out" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n1)"
  [[ -n "$got" ]] || got="$(printf '%s\n' "$out" | grep -oE '[0-9]+\.[0-9]+' | head -n1)"
  if [[ -z "$got" ]]; then
    printf '%s⚠%s %s present, but its version string could not be parsed (pinned %s)\n' "$c_yel" "$c_rst" "$bin" "$want"
  elif [[ "$got" == "$want" ]]; then
    pass "$bin → $got   (matches pin)"
  else
    printf '%s⚠%s %s → %s does NOT match pinned %s — align with ci.yml to mirror CI\n' "$c_yel" "$c_rst" "$bin" "$got" "$want"
  fi
}
_doctor shellcheck "$(_ver SHELLCHECK_VERSION)" shellcheck --version
_doctor luacheck "$(_ver LUACHECK_VERSION)" luacheck --version
_doctor nvim "$(_ver NVIM_VERSION)" nvim --version
_doctor markdownlint-cli2 "$(_ver MARKDOWNLINT_VERSION)" markdownlint-cli2 --version
_doctor actionlint "$(_ver ACTIONLINT_VERSION)" actionlint --version
if have zsh; then pass "zsh → $(zsh --version | grep -oE '[0-9]+\.[0-9]+' | head -n1)"; else skip "zsh absent (the behavioral tests need it)"; fi
if have python3; then pass "python3 present (toml/yaml parse checks)"; else skip "python3 absent (toml/yaml checks skip)"; fi

# --doctor stops here: it's the read-only triage, so no audit run and no green/fix verdict.
if ((DOCTOR_ONLY)); then
  printf '\n%s✓ doctor complete (read-only — no install, no audit). Run: make setup%s\n' "$c_grn" "$c_rst"
  exit 0
fi

# ── 4. prove the box green ────────────────────────────────────────────────────
hdr "running the audit"
if ./scripts/audit-core.sh --quiet; then
  printf '\n%s✓ setup complete — the audit is green. Run: make audit%s\n' "$c_grn" "$c_rst"
else
  printf '\n%s! setup finished, but the audit reported issues above — fix, then re-run.%s\n' "$c_yel" "$c_rst" >&2
  exit 1
fi
